# Write your MySQL query statement below 

WITH CTE AS (SELECT D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE, E.SALARY AS SALARY,
            DENSE_RANK() OVER (PARTITION BY D.ID ORDER BY E.SALARY DESC) AS RNK
            FROM EMPLOYEE E
            JOIN DEPARTMENT D ON E.DEPARTMENTID = D.ID)

SELECT DEPARTMENT, EMPLOYEE, SALARY
FROM CTE 
WHERE RNK <= 3 
