# Write your MySQL query statement below
-- THE NO OF MOVING AVG I SHOULD TAKE IS COUNT(DISTINCT VISITED_ON) MINUS 6

SELECT DISTINCT visited_on,
       SUM(amount) OVER(ORDER BY visited_on ASC RANGE BETWEEN INTERVAL 6 DAY PRECEDING AND CURRENT ROW) AS amount,
       ROUND((SUM(amount) OVER(ORDER BY visited_on ASC RANGE BETWEEN INTERVAL 6 DAY PRECEDING AND CURRENT ROW))/7,2) AS average_amount
FROM Customer
LIMIT 100000000000 OFFSET 6 ;